### PR TITLE
Add subtitles feature

### PR DESCRIPTION
**Pull request by KyleKun**
Added a new text field to add subtitles that can be seen in a player that supports it.
Fixed some localized strings.

### CODE REVIEW

**Comment by KyleKun** [comment]
Hey @daoxve , would you mind taking a quick look just to check if I am not doing any mess here :p

**Review by daoxve — COMMENTED** [review]
I think this would work without any conflicts with my branch 🚀

**Review by daoxve — APPROVED** [review]
LGTM! :)

**Comment by KristjanLaane** [comment]
What does it mean in a player that supports them? Would be really great to have an option to hardcode the subtitles into the image when making a movie.

**Comment by KyleKun** [comment]
> What does it mean in a player that supports them? Would be really great to have an option to hardcode the subtitles into the image when making a movie. 

Most players support loading subtitles, tbh I see no clear reason to hardcode when you can enable / disable as wanted, I see a disadvantage where large subtitles (3+ lines) would compromise the view of what's behind.

**Comment by KristjanLaane** [comment]
I watched the movie from your app in Google Photos (it syncs nicely into it automatically from my phone), but dont see any subtitles. I would like to share the movie with people from Google Photos and for them to see the subtitle descriptions as well, but unfortunately that use case is not supported. 
I also tried to see if VLC on my desktop would show the subtitles as a workaround, but it could not detect any subtitle track in the file. Is there any specific player you could highlight that should show the subtitles?
And thank you for an amazing app btw!

**Comment by KyleKun** [comment]
> I watched the movie from your app in Google Photos (it syncs nicely into it automatically from my phone), but dont see any subtitles. I would like to share the movie with people from Google Photos and for them to see the subtitle descriptions as well, but unfortunately that use case is not supported. 
> I also tried to see if VLC on my desktop would show the subtitles as a workaround, but it could not detect any subtitle track in the file. Is there any specific player you could highlight that should show the subtitles?
> And thank you for an amazing app btw! 

Curiously it seems Google Photos doesn't support subtitles: https://support.google.com/photos/thread/145742516?hl=en&msgid=145824388

VLC should show them, do they show up in the calendar view as "Edit subtitles"?

And you're welcome :)

**Comment by KristjanLaane** [comment]
I discovered the reason VLC did not show subtitles - because I downloaded the movie file from Google Photos and Google Photos converts the video on upload and appears to remove the subtitle track in the process. 
When I copied the file directly from the phone to my desktop then the subtitle track was present as it should be. 
This process is cumbersome though, it’s hassle to download from phone, send it to people I want to share it with and ask them to download it to the desktop and use VLC. Even if they download it to their phone then Android native video player does not seem to support subtitles either. Do you know of any online service I can upload my video to that shows subtitles automatically and that I could share a link to so at least the people I share it with dont have to do any work to see the subtitles?

**Comment by KyleKun** [comment]
> I discovered the reason VLC did not show subtitles - because I downloaded the movie file from Google Photos and Google Photos converts the video on upload and appears to remove the subtitle track in the process. 
> When I copied the file directly from the phone to my desktop then the subtitle track was present as it should be. 
> This process is cumbersome though, it’s hassle to download from phone, send it to people I want to share it with and ask them to download it to the desktop and use VLC. Even if they download it to their phone then Android native video player does not seem to support subtitles either. Do you know of any online service I can upload my video to that shows subtitles automatically and that I could share a link to so at least the people I share it with dont have to do any work to see the subtitles?

Yes, Google Drive, I just tested and it works, the only thing is that you need to tap the CC button and select the "unknown" option to show the subtitles.

**Pull request merged**
